title: "Harris Landgarten"
description: "AI, Market Theory, and Innovation"
url: "https://www.harrislandgarten.com"
baseurl: ""
name: "Harris Landgarten"
email: "harrisl@deeplearntech.com"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
