---
layout: single
title: "Welcome"
permalink: /
author_profile: true
sidebar:
  nav: "main"
---

Welcome to my personal site. I’m Harris Landgarten — inventor, trader, and AI innovator.

Explore my work in market theory, cutting-edge AI modeling, and practical product design.

