title: "Harris Landgarten"
description: "AI, Market Theory, and Innovation"
url: "https://www.harrislandgarten.com"
baseurl: ""
email: "harrisl@deeplearntech.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-data

markdown: kramdown
kramdown:
  input: GFM

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  # …your existing defaults…
include:
  - assets/css
  - assets/js

